version: '3.9'

services:
    db:
        image: mongo
        container_name: db
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=dio
            - MONGO_INITDB_ROOT_PASSWORD=dio
        ports:
            - "27017:27017"
        volumes:
            - C:/Users/nicol/OneDrive/Documentos/DIO/DIO-Java-BancoPan/Java-Avancado/introducao_mongodb:/data/db
